import Foundation

/// Texts in Russian and Uzbek (Latin), the two languages of the bot. The person's choice comes
/// from the server (`Me.locale`) and is shared with the bot.
enum Lang: String, CaseIterable, Identifiable {
    case ru, uz
    var id: String { rawValue }
    var title: String { self == .ru ? "Русский" : "Oʻzbekcha" }
    var localeId: String { self == .ru ? "ru_RU" : "uz_Latn_UZ" }
}

struct Strings {
    let lang: Lang

    func callAsFunction(_ key: String) -> String {
        let table = lang == .ru ? Strings.ru : Strings.uz
        return table[key] ?? Strings.ru[key] ?? key
    }

    func unit(_ code: String) -> String { self("unit.\(code)") }
    func food(_ code: String) -> String { self("food.\(code)") }
    func courseStatus(_ code: String) -> String { self("status.\(code)") }
    func doseStatus(_ code: String) -> String { self("dose.\(code)") }
    func reason(_ code: String) -> String { self("reason.\(code)") }

    static let ru: [String: String] = [
        "app.name": "MedCourse",
        "signin.title": "Ваш курс лечения — под рукой",
        "signin.subtitle": "Приёмы на сегодня, курс от врача и история — в одном месте. Напоминания по-прежнему приходят в Telegram.",
        "signin.button": "Войти через Telegram",
        "signin.waiting": "Подтвердите вход в боте MedCourse и вернитесь сюда",
        "signin.openAgain": "Открыть бот ещё раз",
        "signin.cancel": "Отмена",
        "signin.expired": "Время на подтверждение вышло. Попробуйте ещё раз.",
        "signin.noTelegram": "Не удалось открыть Telegram. Установите его и попробуйте снова.",
        "signin.demo": "Посмотреть без входа",
        "demo.badge": "Демо",
        "demo.banner": "Демо-режим: данные ненастоящие, ничего никуда не отправляется. «Выйти» — вернуться ко входу.",
        "tab.today": "Сегодня",
        "tab.courses": "Курсы",
        "tab.settings": "Профиль",
        "today.greeting.morning": "Доброе утро",
        "today.greeting.day": "Добрый день",
        "today.greeting.evening": "Добрый вечер",
        "today.progress": "%d из %d приёмов",
        "today.empty.title": "На сегодня приёмов нет",
        "today.empty.text": "Когда врач пришлёт курс и вы его начнёте, приёмы появятся здесь.",
        "today.allDone": "Все приёмы на сегодня отмечены",
        "today.next": "Следующий",
        "today.asNeeded": "По необходимости",
        "action.take": "Выпил(а)",
        "action.takeLate": "Всё-таки выпил(а)",
        "action.skip": "Пропустить",
        "action.later": "Позже",
        "action.undo": "Отменить ответ",
        "action.laterMinutes": "Через %d мин",
        "action.cancel": "Отмена",
        "action.retry": "Повторить",
        "action.close": "Закрыть",
        "skip.title": "Почему пропускаете?",
        "skip.note": "Своими словами (необязательно)",
        "skip.send": "Пропустить приём",
        "reason.FORGOT": "Забыл(а)",
        "reason.NO_MEDICATION": "Нет лекарства",
        "reason.OTHER": "Другая причина",
        "prn.take": "Принял(а)",
        "prn.count": "За сутки: %d из %d",
        "prn.overLimit": "Это сверх назначенного. Врач получит уведомление.",
        "prn.undo": "Отменить отметку",
        "dose.SCHEDULED": "Ожидает",
        "dose.NOTIFIED": "Пора принять",
        "dose.SNOOZED": "Отложен",
        "dose.TAKEN": "Принят",
        "dose.TAKEN_LATE": "Принят с опозданием",
        "dose.SKIPPED": "Пропущен",
        "dose.MISSED": "Не отмечен",
        "dose.SUPERSEDED": "Отменён",
        "courses.title": "Курсы",
        "courses.empty.title": "Курсов пока нет",
        "courses.empty.text": "Курс появится здесь, когда врач его отправит.",
        "courses.current": "Текущие",
        "courses.past": "Прошлые",
        "course.from": "Курс от %@",
        "course.doctor": "Врач",
        "course.medications": "Препараты",
        "course.days": "%d дн.",
        "course.day": "День %d из %d",
        "course.adherence": "Вовремя",
        "course.taken": "Принято",
        "course.late": "С опозданием",
        "course.skipped": "Пропущено",
        "course.missed": "Не отмечено",
        "course.history": "История по дням",
        "course.start": "Начать курс",
        "course.startConfirm": "Начать курс сегодня?",
        "course.startDetails": "День 1 — %@, последний день — %@. Сегодня приёмов: %d, всего: %d.",
        "course.startBy": "Начать до %@",
        "course.started": "Курс начат",
        "course.changeTitle": "Врач изменил план",
        "course.changeText": "Новый план начнёт действовать после вашего согласия.",
        "course.changeAccept": "Принять новый план",
        "course.added": "Добавлено",
        "course.removed": "Убрано",
        "course.pause": "Попросить врача о паузе",
        "course.pauseText": "Врач получит вашу просьбу. Не прекращайте приём сами, пока врач не ответит.",
        "course.pauseSent": "Просьба отправлена врачу",
        "course.pauseAlready": "Вы уже просили сегодня",
        "course.asNeeded": "по необходимости, до %d раз в сутки",
        "course.instructions": "Указания врача",
        "refusal.ALREADY_STARTED": "Курс уже начат.",
        "refusal.WITHDRAWN": "Врач отозвал курс.",
        "refusal.OUTSIDE_WINDOW": "Сейчас курс начать нельзя: вне срока начала.",
        "refusal.DOCTOR_UNAVAILABLE": "Врач сейчас недоступен. Начать курс нельзя.",
        "refusal.NOTHING_LEFT": "Все приёмы курса уже в прошлом.",
        "status.PENDING_PATIENT": "Ждёт начала",
        "status.ACTIVE": "Идёт",
        "status.PAUSED": "На паузе",
        "status.COMPLETED": "Завершён",
        "status.CANCELLED": "Отменён",
        "status.EXPIRED_NOT_STARTED": "Не начат вовремя",
        "status.ARCHIVED": "В архиве",
        "status.CANCELLATION_REVIEW": "Отмена на рассмотрении",
        "status.DRAFT": "Черновик",
        "food.BEFORE_MEAL": "до еды",
        "food.WITH_MEAL": "во время еды",
        "food.AFTER_MEAL": "после еды",
        "food.ANY": "независимо от еды",
        "unit.MG": "мг", "unit.G": "г", "unit.MCG": "мкг", "unit.ML": "мл",
        "unit.TABLET": "табл.", "unit.CAPSULE": "капс.", "unit.DROP": "кап.",
        "unit.IU": "МЕ", "unit.PUFF": "вдох", "unit.SACHET": "саше", "unit.OTHER": "ед.",
        "history.empty": "В этом курсе ещё не было приёмов.",
        "history.prn": "по необходимости",
        "history.older": "Раньше",
        "settings.title": "Профиль",
        "settings.language": "Язык",
        "settings.timezone": "Часовой пояс",
        "settings.reminders": "Напоминания",
        "settings.remindersText": "Напоминания о приёмах приходят в Telegram-бот MedCourse.",
        "settings.openBot": "Открыть бот",
        "settings.privacy": "Согласие и данные",
        "settings.logout": "Выйти",
        "settings.logoutConfirm": "Выйти из приложения? Напоминания в Telegram продолжат приходить.",
        "privacy.title": "Согласие и данные",
        "privacy.consentGiven": "Согласие дано %@",
        "privacy.doctors": "Мои врачи",
        "privacy.withdraw": "Отозвать согласие",
        "privacy.withdrawText": "Все курсы остановятся, врачи перестанут видеть ваши данные. Вернуть согласие можно в боте.",
        "privacy.delete": "Удалить мои данные",
        "privacy.deleteText": "Доступ закроется сразу, данные будут обезличены через 30 дней. До этого запрос можно отменить.",
        "privacy.deletionDue": "Данные будут удалены %@",
        "privacy.cancelDeletion": "Отменить удаление",
        "privacy.restricted": "Согласие отозвано или запрошено удаление. Пока доступен только этот раздел.",
        "privacy.restoreInBot": "Чтобы вернуть согласие, откройте бот.",
        "error.network": "Нет связи с сервером. Проверьте интернет.",
        "error.generic": "Что-то пошло не так. Попробуйте ещё раз.",
        "error.too_early": "Слишком рано: отметить можно не раньше чем за час до приёма.",
        "error.too_late": "Срок прошёл — можно отметить только «всё-таки выпил(а)».",
        "error.snooze_not_allowed": "Отложить на столько уже нельзя.",
        "error.not_correctable": "Изменить ответ уже нельзя: прошёл час.",
        "error.nothing_pending": "Изменений, ожидающих ответа, нет.",
    ]

    static let uz: [String: String] = [
        "app.name": "MedCourse",
        "signin.title": "Davolash kursingiz — qoʻl ostida",
        "signin.subtitle": "Bugungi qabullar, shifokor kursi va tarix — bir joyda. Eslatmalar avvalgidek Telegram'ga keladi.",
        "signin.button": "Telegram orqali kirish",
        "signin.waiting": "MedCourse botida kirishni tasdiqlang va shu yerga qayting",
        "signin.openAgain": "Botni yana ochish",
        "signin.cancel": "Bekor qilish",
        "signin.expired": "Tasdiqlash vaqti tugadi. Yana urinib koʻring.",
        "signin.noTelegram": "Telegram ochilmadi. Uni oʻrnating va qayta urinib koʻring.",
        "signin.demo": "Kirmasdan koʻrish",
        "demo.badge": "Demo",
        "demo.banner": "Demo rejim: maʼlumotlar haqiqiy emas, hech narsa yuborilmaydi. «Chiqish» — kirishga qaytish.",
        "tab.today": "Bugun",
        "tab.courses": "Kurslar",
        "tab.settings": "Profil",
        "today.greeting.morning": "Xayrli tong",
        "today.greeting.day": "Xayrli kun",
        "today.greeting.evening": "Xayrli kech",
        "today.progress": "%d / %d qabul",
        "today.empty.title": "Bugun qabullar yoʻq",
        "today.empty.text": "Shifokor kurs yuborib, siz uni boshlaganingizda qabullar shu yerda paydo boʻladi.",
        "today.allDone": "Bugungi barcha qabullar belgilandi",
        "today.next": "Keyingisi",
        "today.asNeeded": "Zaruratga qarab",
        "action.take": "Ichdim",
        "action.takeLate": "Baribir ichdim",
        "action.skip": "Oʻtkazib yuborish",
        "action.later": "Keyinroq",
        "action.undo": "Javobni bekor qilish",
        "action.laterMinutes": "%d daqiqadan keyin",
        "action.cancel": "Bekor qilish",
        "action.retry": "Qayta urinish",
        "action.close": "Yopish",
        "skip.title": "Nega oʻtkazib yuboryapsiz?",
        "skip.note": "Oʻz soʻzlaringiz bilan (ixtiyoriy)",
        "skip.send": "Qabulni oʻtkazib yuborish",
        "reason.FORGOT": "Unutdim",
        "reason.NO_MEDICATION": "Dori yoʻq",
        "reason.OTHER": "Boshqa sabab",
        "prn.take": "Qabul qildim",
        "prn.count": "Bir sutkada: %d / %d",
        "prn.overLimit": "Bu belgilangandan ortiq. Shifokorga xabar beriladi.",
        "prn.undo": "Belgini bekor qilish",
        "dose.SCHEDULED": "Kutilmoqda",
        "dose.NOTIFIED": "Qabul vaqti",
        "dose.SNOOZED": "Kechiktirilgan",
        "dose.TAKEN": "Qabul qilingan",
        "dose.TAKEN_LATE": "Kechikib qabul qilingan",
        "dose.SKIPPED": "Oʻtkazib yuborilgan",
        "dose.MISSED": "Belgilanmagan",
        "dose.SUPERSEDED": "Bekor qilingan",
        "courses.title": "Kurslar",
        "courses.empty.title": "Hozircha kurslar yoʻq",
        "courses.empty.text": "Shifokor kurs yuborganda u shu yerda paydo boʻladi.",
        "courses.current": "Joriy",
        "courses.past": "Oʻtgan",
        "course.from": "%@ dagi kurs",
        "course.doctor": "Shifokor",
        "course.medications": "Dorilar",
        "course.days": "%d kun",
        "course.day": "%d-kun, jami %d",
        "course.adherence": "Oʻz vaqtida",
        "course.taken": "Qabul qilingan",
        "course.late": "Kechikib",
        "course.skipped": "Oʻtkazilgan",
        "course.missed": "Belgilanmagan",
        "course.history": "Kunlar boʻyicha tarix",
        "course.start": "Kursni boshlash",
        "course.startConfirm": "Kursni bugun boshlaysizmi?",
        "course.startDetails": "1-kun — %@, oxirgi kun — %@. Bugun qabullar: %d, jami: %d.",
        "course.startBy": "%@ gacha boshlang",
        "course.started": "Kurs boshlandi",
        "course.changeTitle": "Shifokor rejani oʻzgartirdi",
        "course.changeText": "Yangi reja siz rozi boʻlganingizdan keyin kuchga kiradi.",
        "course.changeAccept": "Yangi rejani qabul qilish",
        "course.added": "Qoʻshildi",
        "course.removed": "Olib tashlandi",
        "course.pause": "Shifokordan pauza soʻrash",
        "course.pauseText": "Shifokor soʻrovingizni oladi. Shifokor javob bermaguncha qabulni oʻzingiz toʻxtatmang.",
        "course.pauseSent": "Soʻrov shifokorga yuborildi",
        "course.pauseAlready": "Bugun allaqachon soʻragansiz",
        "course.asNeeded": "zaruratga qarab, sutkada %d martagacha",
        "course.instructions": "Shifokor koʻrsatmalari",
        "refusal.ALREADY_STARTED": "Kurs allaqachon boshlangan.",
        "refusal.WITHDRAWN": "Shifokor kursni qaytarib oldi.",
        "refusal.OUTSIDE_WINDOW": "Hozir kursni boshlab boʻlmaydi: boshlash muddati tashqarisida.",
        "refusal.DOCTOR_UNAVAILABLE": "Shifokor hozir mavjud emas. Kursni boshlab boʻlmaydi.",
        "refusal.NOTHING_LEFT": "Kursning barcha qabullari oʻtib ketgan.",
        "status.PENDING_PATIENT": "Boshlanishini kutmoqda",
        "status.ACTIVE": "Davom etmoqda",
        "status.PAUSED": "Toʻxtatilgan",
        "status.COMPLETED": "Tugallangan",
        "status.CANCELLED": "Bekor qilingan",
        "status.EXPIRED_NOT_STARTED": "Muddatida boshlanmagan",
        "status.ARCHIVED": "Arxivda",
        "status.CANCELLATION_REVIEW": "Bekor qilish koʻrib chiqilmoqda",
        "status.DRAFT": "Qoralama",
        "food.BEFORE_MEAL": "ovqatdan oldin",
        "food.WITH_MEAL": "ovqat vaqtida",
        "food.AFTER_MEAL": "ovqatdan keyin",
        "food.ANY": "ovqatga bogʻliq emas",
        "unit.MG": "mg", "unit.G": "g", "unit.MCG": "mkg", "unit.ML": "ml",
        "unit.TABLET": "tabl.", "unit.CAPSULE": "kaps.", "unit.DROP": "tomchi",
        "unit.IU": "XB", "unit.PUFF": "nafas", "unit.SACHET": "sashe", "unit.OTHER": "birl.",
        "history.empty": "Bu kursda hali qabullar boʻlmagan.",
        "history.prn": "zaruratga qarab",
        "history.older": "Avvalroq",
        "settings.title": "Profil",
        "settings.language": "Til",
        "settings.timezone": "Vaqt mintaqasi",
        "settings.reminders": "Eslatmalar",
        "settings.remindersText": "Qabul eslatmalari MedCourse Telegram-botiga keladi.",
        "settings.openBot": "Botni ochish",
        "settings.privacy": "Rozilik va maʼlumotlar",
        "settings.logout": "Chiqish",
        "settings.logoutConfirm": "Ilovadan chiqasizmi? Telegram'dagi eslatmalar kelishda davom etadi.",
        "privacy.title": "Rozilik va maʼlumotlar",
        "privacy.consentGiven": "Rozilik berilgan: %@",
        "privacy.doctors": "Shifokorlarim",
        "privacy.withdraw": "Rozilikni qaytarib olish",
        "privacy.withdrawText": "Barcha kurslar toʻxtaydi, shifokorlar maʼlumotlaringizni koʻrmaydi. Rozilikni botda qaytarish mumkin.",
        "privacy.delete": "Maʼlumotlarimni oʻchirish",
        "privacy.deleteText": "Kirish darhol yopiladi, maʼlumotlar 30 kundan keyin anonimlashtiriladi. Ungacha soʻrovni bekor qilish mumkin.",
        "privacy.deletionDue": "Maʼlumotlar %@ da oʻchiriladi",
        "privacy.cancelDeletion": "Oʻchirishni bekor qilish",
        "privacy.restricted": "Rozilik qaytarib olingan yoki oʻchirish soʻralgan. Hozircha faqat shu boʻlim ochiq.",
        "privacy.restoreInBot": "Rozilikni qaytarish uchun botni oching.",
        "error.network": "Server bilan aloqa yoʻq. Internetni tekshiring.",
        "error.generic": "Nimadir notoʻgʻri ketdi. Yana urinib koʻring.",
        "error.too_early": "Juda erta: qabuldan bir soatdan oldin belgilab boʻlmaydi.",
        "error.too_late": "Muddat oʻtdi — faqat «baribir ichdim» deb belgilash mumkin.",
        "error.snooze_not_allowed": "Bunchalik kechiktirib boʻlmaydi.",
        "error.not_correctable": "Javobni endi oʻzgartirib boʻlmaydi: bir soat oʻtdi.",
        "error.nothing_pending": "Javob kutayotgan oʻzgarish yoʻq.",
    ]
}
