// Writes src/font.generated.ts: the two DejaVu Sans faces the PDF report is set in, as base64.
// The fonts have to travel inside the code: each application is built into one file with no
// node_modules beside it, and the same module has to load under tsx, vitest and the bundle.
// Run with `pnpm --filter @medcourse/report make-font` after changing the font package version.
import { readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const packageFile = require.resolve('dejavu-fonts-ttf/package.json');
const { version } = JSON.parse(readFileSync(packageFile, 'utf8'));
const fonts = dirname(packageFile);

const WIDTH = 100;
function literal(file) {
  const base64 = readFileSync(join(fonts, 'ttf', file)).toString('base64');
  const lines = [];
  for (let at = 0; at < base64.length; at += WIDTH) {
    lines.push(`  '${base64.slice(at, at + WIDTH)}',`);
  }
  return `[\n${lines.join('\n')}\n].join('')`;
}

writeFileSync(
  join(here, '..', 'src', 'font.generated.ts'),
  [
    `// Generated by scripts/make-font.mjs from dejavu-fonts-ttf ${version}. Do not edit by hand.`,
    '// DejaVu Sans: Latin, Cyrillic and the Uzbek modifier letter (U+02BB). Licence: FONT-LICENSE.txt.',
    '',
    `export const FONT_REGULAR_BASE64: string = ${literal('DejaVuSans.ttf')};`,
    '',
    `export const FONT_BOLD_BASE64: string = ${literal('DejaVuSans-Bold.ttf')};`,
    '',
  ].join('\n'),
);
copyFileSync(join(fonts, 'LICENSE'), join(here, '..', 'FONT-LICENSE.txt'));
console.log(`font.generated.ts written from dejavu-fonts-ttf ${version}`);
